### PR TITLE
For public view, disable delete button and fix share-link.

### LINKED ISSUE #261: Disable object sharing for read-only policy.
share-auth

We can basically keep the share button but point it to full URL instead of presigned URL.

### PR DESCRIPTION
**Pull request by krishnasrinivas**
Fixes #261 #260

### CODE REVIEW

File: app/js/components/ObjectsList.js [hunk 1]
```diff
@@ -27,12 +27,15 @@ let ObjectsList = ({ objects, currentPath, selectPrefix, dataType, showDeleteCon
         let lastModified = object.name.endsWith('/') ? '-' : Moment(object.lastModified).format('lll')
         let loadingClass = loadPath === `${currentPath}${object.name}` ? 'fesl-loading' : ''
         let actionButtons = ''
+        let deleteButton = ''
+        if (web.LoggedIn())
+	  deleteButton = <a href="" className="fiad-action" onClick={(e) => showDeleteConfirmation(e, `${currentPath}${object.name}`)} ><i className="fa fa-trash"></i></a>
```
Comment (harshavardhana) [inline app/js/components/ObjectsList.js]: Is this tabbing correct?

**Comment by harshavardhana** [comment]
Ping @krishnasrinivas - added one comment.

File: app/js/components/ObjectsList.js (hunk 1 above)
Comment (krishnasrinivas) [inline app/js/components/ObjectsList.js]: github is showing 1 space instead of 2. btw the indentation of miniobrowser source is inconsistent, will separately indent things properly.
